### PR TITLE
Support Stackage LTS 13

### PR DESCRIPTION
**Pull request by tfausak**
This gets the project building with the LTS 13 resolver. It's an alternative to 47fe19a543c4044fcf148ea71b24b718b8bd186f. I know that y'all are working on big changes here, so I don't really expect this to be merged. I just wanted to make a PR to track my changes. Carry on 😄

### CODE REVIEW

**Comment by telser** [comment]
@tfausak Thanks for this! I've actually got a local branch that encompasses many of the changes. Are you using LTS-13 yet? If so, stepping forward 47fe19a seems like a good idea to me. As it is, I'll probably pick out the changes that I had made along with ones from here to go ahead and get merged in via a separate branch. Particularly the Semigroup and MonadFail stuff.

**Comment by tfausak** [comment]
Yup, we're on LTS 13. I tried to use 47fe19a but it didn't work for some reason. I should have written down what happened. I think it was related to `MonadFail`?

**Comment by telser** [comment]
It would definitely be related to `MonadFail`. I don't expect it to be terribly difficult to get that to a place where it would work for you.

**Comment by onslaughtq** [comment]
Just a thought, but when our account has the capability, you might consider closing and re-opening this PR as a draft PR (https://github.blog/2019-02-14-introducing-draft-pull-requests/), though you would lose the current conversation history

**Comment by telser** [comment]
Closing this as the 0.9_development branch has been used with LTSs past 13 for quite some time now and it was recently merged into the primary branch.

**Pull request closed without merging**
