### PR TITLE
Adds `planTraversable`, a generalization of `planList`

### PR DESCRIPTION
**Pull request by jlavelle**

### CODE REVIEW

**Comment by ysangkok** [comment]
This would be nice when working with NonEmpty, which are pretty common. So I am a fan.

**Review by jbrechtel — APPROVED** [review]
:+1:

**Comment by jbrechtel** [comment]
Maybe @telser or @onslaughtq should chime in before it's merged in the event we need docs updated or explicit test coverage for this.

**Comment by jlavelle** [comment]
I added a test case

**Review by telser — APPROVED** [review]
Seems like a reasonable convenience function to me. 

Thanks for fixing the workflows too!

**Pull request merged**
