### PR TITLE
small fixes

### PR DESCRIPTION
**Pull request by cdepillabout**
I've gone through and fixed up a few small things.  There shouldn't be anything *too* controversial here.

Here's a list of what I've changed:

*   Add a `stack.yaml` file to make it easier to use with stack.
*   Add a `.travis.yml` file to make it possible to test with Travis-CI.
    *   This is a template taken from [here](https://docs.haskellstack.org/en/stable/travis_ci/).  I use this same setup in a few of my own packages and it seems to work pretty well.
    *   Currently building with stack is not working on travis because HDBC-postgres is not available on stackage, but it would be nice to add this at some later date.
    *   I enabled travis on my own repository.  You can see how the tests look [here](https://travis-ci.org/cdepillabout/orville).  Once this PR is merged in, you'll have to enable travis for this `flipstone/orville` repository.
*   Add a simple skeleton `README.md`.
*   Fixup a few small things in the `.cabal file`.
    *   Add some additional GHC warning flags.  See [here](https://functor.tokyo/blog/2017-07-28-ghc-warnings-you-should-enable) for more info.
    *   I changed the license from `AllRightsReserved` to `MIT` because the `LICENSE` file is an MIT license.  I assumed `AllRightsReserved` was the original default value created when doing `cabal new`, but let me know if this was intentional.
*   Fix a couple small compiler warnings.

### CODE REVIEW

**Comment by qxjit** [comment]
@cdepillabout Sorry I couldn't get to this sooner. I'm back in America now and have overcome the jet-lag finally I think.

@14to9 Sorry you didn't have any context from the Tokyo meetup with @cdepillabout when this came in ;)

To be honest, I've never set up a travis build from github. Do we just have to enable it in the settings for the repo, or is there a bunch of travis account registration, etc to do as well?

**Comment by cdepillabout** [comment]
@14to9 Yeah sorry from me too!  I should have mentioned I met David in Tokyo at a Haskell meetup and he told me about Orville!

@qxjit Thanks for taking a look at this PR!

Enabling travis for a github repo is pretty simple.  First go to https://travis-ci.org/ and log in with your github account.  Then go to https://travis-ci.org/profile/.  There should be a link that says "Is an organization missing? Review and add your authorized organizations."  Click on it and add the flipstone github organization.  When that is enabled I think you should be able to go to https://travis-ci.org/profile/flipstone and click the button to enable travis for this repository.

If you merge this PR in, I believe a travis build should start.  The link in the README should also become active.

**Comment by cdepillabout** [comment]
@14to9 I agree that the README needs some examples.  For my next PR, I was planning on adding an example Haskell file showing how to use Orville.  This would be mostly for new users looking for an example of how to use Orville.

After figuring that out myself, I was planning on adding some simpler examples to the README.

**Comment by qxjit** [comment]
@cdepillabout Awesome, thank you! I've set up the build, and it is green ❤️

**Pull request merged**
